Cw2 2
alkor63/courseProj2 pull request #1
Opened 2023-02-05 17:03 UTC by alkor63

2023-02-05 20:19 UTC, alekseykoshelev requested changes

2023-02-05 20:19 UTC, alekseykoshelev commented on src/CourseWork2code/DailyTask.java
> +    private final LocalDateTime dateTime;
Такие же поля есть в родительском классе, тут их можно не дублировать.

2023-02-05 20:19 UTC, alekseykoshelev commented on src/CourseWork2code/IncorrectArgumentException.java
> +        return "*** IncorrectArgumentException - некорректный титул задачи ***";
В таком случае, раз тут поле есть, можно его сюда добавить)

2023-02-05 20:19 UTC, alekseykoshelev commented on src/CourseWork2code/MonthlyTask.java
> +        if (inputDate.getDayOfMonth() == taskDate.getDayOfMonth())
Условие правильно, можно упростить `return inputDate.getDayOfMonth() == taskDate.getDayOfMonth();`

2023-02-05 20:19 UTC, alekseykoshelev commented on src/CourseWork2code/OneTimeTask.java
> +    private final LocalDateTime dateTime;
Аналогичный момент по полям.

2023-02-05 20:19 UTC, alekseykoshelev commented on src/Main.java
> +    private static void printMenu1() {
А почему в конце 1?)

2023-02-05 20:19 UTC, alekseykoshelev commented on src/CourseWork2code/TaskService.java
> +        Scanner scanner2 = new Scanner(System.in);
Получается в этом методе 3 сканнера, один это аргумент, 2 ты создал. А зачем так много?

2023-02-05 20:19 UTC, alekseykoshelev commented on src/CourseWork2code/TaskService.java
> +                taskTyp = Type.valueOf("ЛИЧНАЯ");
Вариант интересный, но ведь он не будет работать. Можно же использовать `Type.PERSONAL`

2023-02-05 20:19 UTC, alekseykoshelev commented on src/CourseWork2code/TaskService.java
> +    public static void inputTask(Scanner scanner, Map<Integer, Task> tasks) {
Не совсем понимаю почему в каждом методе есть аргумент типа `Map<Integer, Task> tasks`. Ведь тут у тебя есть поля такого же типа, ты можешь к нему обращаться не передавая как аргумент. Поле, кстати, можно сделать private

2023-02-05 20:19 UTC, alekseykoshelev commented on src/CourseWork2code/TaskService.java
> +    public static void updateDescription(Map<Integer, Task> tasks) {
Сюда, как вариант, можно передавать сканнер аргументом.

2023-02-05 20:19 UTC, alekseykoshelev commented on src/CourseWork2code/TaskService.java
> +            taskSet.add(task);
По поводу аргумента я понял, но в таком случае лучше по другому назвать переменную, иначе вообще не понятно, что она хранит удаленные задачи.

2023-02-05 20:36 UTC, alekseykoshelev commented on src/TextCounter/TextScanner.java
> +        Scanner scan = new Scanner(inputText);
В целом верно, но можно чуть проще. Через метод `inputText.split(" ")`

2023-02-05 20:36 UTC, alekseykoshelev commented on src/TextCounter/TextScanner.java
> +        HashMap<String, Integer> listOfWords = new HashMap<String, Integer>();
Ну это не совсем list, скорее map)

2023-02-05 20:36 UTC, alekseykoshelev commented on src/TextCounter/TextScanner.java
> +                listOfWords.remove(word); //first remove it (can't have duplicate keys)
Можно не удалять, можно сразу делать put. значение просто перезапишется

2023-02-06 10:19 UTC, alkor63 commented on src/CourseWork2code/DailyTask.java
> +    private final LocalDateTime dateTime;
Почему-то не получается, если не добавлять дату в качестве аргумента.  
А по логике задачи я дату не передаю снаружи, а присваиваю текущую дату при создании объекта

2023-02-06 10:19 UTC, alkor63 commented on src/CourseWork2code/IncorrectArgumentException.java
> +        return "*** IncorrectArgumentException - некорректный титул задачи ***";
Здесь речь про титул задачи = null или пустышка. Решил, что вывод пустоты информации не добавит

2023-02-06 10:20 UTC, alkor63 commented on src/CourseWork2code/MonthlyTask.java
> +        if (inputDate.getDayOfMonth() == taskDate.getDayOfMonth())
+

2023-02-06 10:20 UTC, alkor63 commented on src/Main.java
> +    private static void printMenu1() {
Исторически) Когда начинал писать этот код уже понимал, что у меня будет 3 меню, но про разные классы еще не думал

2023-02-06 10:20 UTC, alkor63 commented on src/CourseWork2code/TaskService.java
> +        Scanner scanner2 = new Scanner(System.in);
Перестраховка. Не знаю, что у сканера под капотом, но убедился, что текст, числа и, например, даты лучше вводить через разные сканеры.
scanner1 убрал.

2023-02-06 10:20 UTC, alkor63 commented on src/CourseWork2code/TaskService.java
> +                taskTyp = Type.valueOf("ЛИЧНАЯ");
+

2023-02-06 10:20 UTC, alkor63 commented on src/CourseWork2code/TaskService.java
> +    public static void inputTask(Scanner scanner, Map<Integer, Task> tasks) {
Вот здесь я недопонял. Разве у меня есть внутри этого метода (и тех, сто в этом же классе) к мапе, созданной в main без передачи мапы как аргумент? 
какое поле private? модификатор метода в 9 с троке? а метод при этом будет доступен из main ?

2023-02-06 10:20 UTC, alkor63 commented on src/CourseWork2code/TaskService.java
> +            taskSet.add(task);
renamed to archiveRemovedTaskSet

2023-02-06 10:20 UTC, alkor63 commented on src/TextCounter/TextScanner.java
> +        HashMap<String, Integer> listOfWords = new HashMap<String, Integer>();
map с понятным названием Список )

2023-02-06 10:20 UTC, alkor63 commented on src/TextCounter/TextScanner.java
> +                listOfWords.remove(word); //first remove it (can't have duplicate keys)
+

2023-02-21 19:35 UTC, merged